metadata:
  release: LSST_DP02

input:
  catalog_path: examples/demo_catalog/data/input
  catalog_pattern: "*.parquet"
  user_selected_cols:
    - object_id
    - ra
    - dec
    - flux_g
    - fluxerr_g
    - flux_r
    - fluxerr_r
    - is_primary
    - tile
  is_id_in_index: false
  ra_col: ra
  dec_col: dec
  filter:
    enabled: true
    column: is_primary
    value: true
    drop_column_after_filter: true
  initial_cut:
    enabled: true
    column: flux_g
    column_type: flux
    flux_value: 80.0

photometry:
  bands: [g, r]
  band_case: lower_case
  keep_input_columns: false
  magnitude:
    system: AB
    flux_unit: nJy
  measurements:
    - name: cmodel
      input:
        type: flux
        value_pattern: flux_BAND
        error_pattern: fluxerr_BAND
      output:
        type: mag
        value_pattern: mag_BAND
        error_pattern: magerr_BAND

output:
  save_as: hats
  hats_source_save_as: parquet
  hats_artifact_name: demo_hats_catalog
  target_rows_per_part: 2
  order_by: object_id
  col_for_filename: tile

execution:
  executor: local
  local:
    n_workers: 3
    threads_per_worker: 2
    memory_limit: "4GB"
